drop table if exists casedescription;
create table casedescription(
id int(100) primary key AUTO_INCREMENT,
  keyWord1 varchar(1000),
  keyWord2 varchar(1000),
  keyWord3 varchar(1000),
  keyWord4 varchar(1000),
  keyWord5 varchar(1000),
  categoria varchar(1000)
);


INSERT INTO casedescription ( id, keyWord1,keyWord2,keyWord3,keyWord4,keyWord5, categoria )
VALUES
(1,'online',						'distancia',	 null,			 null,			'master',				'estudios'),
(2,'lengua (online)',				'literatura',	'lengua',		'artes',		'online',				'estudios'),
(3,'lengua',						'literatura',	 null,			'artes',		'humanidades',			'estudios'),
(4,'historia (online)',				'patrimonio',	'historia',		'artes',		'online',				'estudios'),
(5,'historia',						'patrimonio',	 null,			'artes',		'humanidades',			'estudios'),
(6,'quimica',						'ciencias',		 null,			 null,			 null,					'estudios'),
(7,'cyta',							'tecnologia',	'alimentos',	'salud',		 null,					'estudios'),
(8,'enfermeria',					'salud',		 null,			 null,			 null,					'estudios'),
(9,'terapia',						'ocupacional',	 null,			'salud',		 null,					'estudios'),
(10,'dade',							'derecho',		'administracion','direccion',	'empresas',				'estudios'),
(11,'derecho politica',				'politica',		'publica',		'doble',		'derecho',				'estudios'),
(12,'ade',							'administracion','direccion',	'empresas',		'sociales',				'estudios'),
(13,'politica (online)',			'politica',		'publica',		'online',		'sociales',				'estudios'),
(14,'politica',						'ciencia',		'publica',		'gestion',		'sociales',				'estudios'),
(15,'audiovisual',					'comunicacion',	 null,			'juridicas',	'sociales',				'estudios'),
(16,'derecho',						'unica',		 null,			'juridicas',	'sociales',				'estudios'),
(17,'educacion social',				'educacion',	'social',		'juridicas',	'sociales',				'estudios'),
(18,'finanzas',						'contabilidad',	 null,			'juridicas',	'sociales',				'estudios'),
(19,'eduacion infantil',			'eduacion',		'infantil',		'maestro',		'sociales',				'estudios'),
(20,'eduacion primaria',			'eduacion',		'primaria',		'maestro',		'sociales',				'estudios'),
(21,'pedagogia',					 null,			 null,			'juridicas',	'sociales',				'estudios'),
(22,'relaciones laborales',			'relaciones',	'laborales',	'recursos',		'humanos',				'estudios'),
(23,'turismo (online)',				'turismo',		'online',		'juridicas',	'sociales',				'estudios'),
(24,'turismo',						 null,			 null,			'juridicas',	'sociales',				'estudios'),
(25,'civil y tecnica',				'civil',		'arquitectura',	'tecnica',		'doble',				'estudios'),
(26,'caminos y tecnica',			'caminos',		'arquitectura',	'tecnica',		'doble',				'estudios'),
(27,'mecanica y electronica',		'mecanica',		'electronica',	'automatica',	'doble',				'estudios'),
(28,'tecnica',						'arquitectura',  null,			 null,			 null,					'estudios'),
(29,'agroalimentaria',				'rural',		'medio',		'ingenieria',	 null,					'estudios'),
(30,'civil',						'ingenieria',	 null,			 null,			 null,					'estudios'),
(31,'organizacion industrial',		 null,			'organizacion',	'industrial',	'ingenieria',			'estudios'),
(32,'caminos',						'tecnologias',	'ingenieria',	 null,			 null,					'estudios'),
(33,'electronica',					'automatica',	'ingenieria',	 null,			 null,					'estudios'),
(34,'informatica (online)',			'informatica',	'online',		'ingenieria',	 null,					'estudios'),
(35,'informatica',					 null,			 null,			'ingenieria',    null,					'estudios'),
(36,'mecanica',						'ingenieria',	 null,			 null,			 null,					'estudios'),

(37,'patrimonio (master)',			'patrimonio',	'comunicacion',	'master',		'artes',				'estudios'),
(38,'vino',							'cultura',		'enoturismo',	'master',		'semipresencial',		'estudios'),
(39,'quimica (master)',				'quimica',		'avanzada',		'master',		'ciencias',				'estudios'),
(40,'evolucion humana',				'evolucion',	'humana',		'master',		'interuniversitario',	'estudios'),
(41,'electroquimica',				'ciencia',		'tecnologia',	'master',		'interuniversitario',	'estudios'),
(42,'seguridad y biotecnologia',	'seguridad',	'biotecnologia','master',		'alimentarias',			'estudios'),
(43,'formacion pedagogica didactica','pedagogica',	'didactica',	'curso',		'formacion',			'estudios'),
(44,'abogacia',						'acceso',		'sociales',		'master',		 null,					'estudios'),
(45,'administracion empresas (master)','administracion','empresas',	'master',		'mba',					'estudios'),
(46,'multimedia',					'desarrollo',	'comunicacion',	'master',		 null,					'estudios'),
(47,'contabilidad',					'avanzada',		'auditoria',	'master',		'cuentas',				'estudios'),
(48,'cooperacion',					'internacional','desarrollo',	'master',		'interuniversitario',	'estudios'),
(49,'derecho y administracion local','derecho',		'administracion','master',		'local',				'estudios'),
(50,'educacion y sociedad inclusivas','educacion',	'sociedad',		'master',		'inclusivas',			'estudios'),
(51,'economia empresa',				'investigacion','administracion','master',		'empresa',				'estudios'),
(52,'profesor',						'educacion',	'secundaria',	'master',		'bachillerato',			'estudios'),
(53,'informatica (master)',			'informatica',	'master',		'ingenieria',	 null,					'estudios'),
(54,'informatica (master, online)',	'informatica',	'master',		'ingenieria',	'online',				'estudios'),
(55,'industrial (master)',			'industrial',	'master',		'ingenieria',	 null,					'estudios'),
(56,'gestion agrosostenible',		'agrosostenible','master',		'ingenieria',	'gestion',				'estudios'),
(57,'caminos (master)',				'caminos',		'master',		'canales',	 	'puertos',				'estudios'),
(58,'edificacion',					'inspeccion',	'master',		'enegetica',	'rehabilitacion',		'estudios'),
(59,'edificacion (online)',			'inspeccion',	'master',		'online',		'rehabilitacion',		'estudios'),
(60,'integridad',					'durabilidad',	'master',		'materiales',	'componentes',			'estudios'),

(61,'titulos',						'propios',		 null,			 null,			 null,					'estudios'),
(62,'idiomas',						'cursos',		'lenguas',		'modernas',		'matricula',			'estudios'),
(63,'internacionales',				'cursos',		'español',		 null,			 null,					'estudios'),
(64,'licenciaturas',				'extinguir',	'ingenierias',	 null,			 null,					'estudios'),
(65,'ubuabierta presenciales',		'cursos',		'presenciales',	'ubuabierta',	 null,					'estudios'),
(66,'ubuabierta online',			'cursos',		'presenciales',	'ubuabierta',	 null,					'estudios'),
(67,'nivel 0',						'cursos',		'0',			'ubuabierta',	'cero',					'estudios'),
(68,'verano',						'cursos',		 null,			'ubuabierta',	 null,					'estudios'),
(69,'infantiles',					'cursos',		'campus',		'ubuabierta',	 null,					'estudios'),
(70,'mayores',						'cursos',		'formacion',	'ubuabierta',	 null,					'estudios'),

(71,'departamentos',				'centros',		 null,			 null,			 null,					'estudios'),
(72,'becas',						'ayudas',		'bonificaciones',null,			 null,					'estudios'),
(73,'calendario',					'academico',	'festivos',		'docencia',		 null,					'estudios'),
(74,'tramites',						'academicos',	'expediente',	'compulsar',	'reconocimiento',		'estudios'),
(75,'calidad',						'docencia',		 null,			 null,			 null,					'estudios'),
(76,'empleo',						'practicas',	'orientacion',	'emprender',	 null,					'estudios'),
(77,'formacion permanente',			'formacion',	'permanente',	'complementaria',null,					'estudios'),
(78,'curriculum docente',			'curriculum',	'docente',		'profesorado',	 null,					'estudios'),

(79,'estudios',						 null,			 null,			 null,			 null,					'estudios'),
(80,'ubuabierta',					 null,			 null,			 null,			 null,					'estudios'),
(81,'ciencia y biotecnologia',		'ciencia',		'alimentaria',	'biotecnologia','doctorado',			'estudios'),
(82,'idustriales y civil',			'industriales',	'ingenieria',	'civil',		'doctorado',			'estudios'),
(83,'quimica (doctorado)',			'quimica',		'avanzada',		 null,			'doctorado',			'estudios'),
(84,'termodinamica fluidos',		'termodinamica','fluidos',		'ingenieria',	'doctorado',			'estudios'),
(85,'humanidades (doctorado)',		'humanidades',	'comunicacion',	 null,			'doctorado',			'estudios'),
(86,'electroquimica',				'ciencia',		'tecnologia',	 null,			'doctorado',			'estudios'),
(87,'sostenibilidad',				'eficiencia',	'energetica',	 null,			'doctorado',			'estudios'),
(88,'educacion (doctorado)',		'educacion',	 null,	 		 null,			'doctorado',			'estudios'),
(89,'economia empresa',				'economia',	 	'empresa',	 	 null,			'doctorado',			'estudios'),
(90,'evolucion humana (doctorado)',	'evolucion',	'paleoecologia','geofisicas',	'doctorado',			'estudios'),
(91,'ciencias juridicas',			'juridicas',	'economicas',	'sociales',		'ciencias',				'estudios'),

(92,'matricula',					 null,			 null,			 null,			 null,					'admisión y matrícula'),
(93,'acceso',						 null,			 null,			 null,			 null,					'admisión y matrícula'),
(94,'bachillerato',					'acceso',		 null,			 null,			 null,					'admisión y matrícula'),
(95,'formacion profesional',		'formacion',	'profesional',	'acceso',		 null,					'admisión y matrícula'),
(96,'mayores de 25',				'mayores',		'25',			'veinticinco',	'acceso',				'admisión y matrícula'),
(97,'mayores de 45',				'mayores',		'45',			'cuarenta y cinco','acceso',			'admisión y matrícula'),
(98,'mayores de 40',				'mayores',		'40',			'cuarenta',		'acceso',				'admisión y matrícula'),
(99,'admision',						 null,			 null,			 null,			 null,					'admisión y matrícula'),
(100,'admision grados',				'admision',		'grados',		 null,			 null,					'admisión y matrícula'),
(101,'admision master',				'admision',		'master',		 null,			 null,					'admisión y matrícula'),
(102,'admision doctorado',			'admision',		'doctorado',	 null,			 null,					'admisión y matrícula'),
(103,'admision titulos propios',	'titulos',		'porpios',		'admision',		 null,					'admisión y matrícula'),
(104,'admision formacion permanente','formacion',	'permanente',	'admision',		 null,					'admisión y matrícula'),
(105,'admision visitantes',			'estudiantes',	'visitantes',	'admision',		 null,					'admisión y matrícula'),
(106,'admision estudios extranjeros','estudiantes',	'estudios',		'extranjeros',	'admision',				'admisión y matrícula'),

(107,'matricula grados',			'matricula',	'grados',		 null,			 null,					'admisión y matrícula'),
(108,'matricula master',			'matricula',	'master',		 null,			 null,					'admisión y matrícula'),
(109,'matricula doctorado',			'matricula',	'doctorado',	 null,			 null,					'admisión y matrícula'),
(110,'matricula titulos propios',	'titulos',		'porpios',		'matricula',	 null,					'admisión y matrícula'),
(111,'matricula titulos extincion',	'titulos',		'extincion',	'matricula',	 null,					'admisión y matrícula'),
(112,'matricula internacional',		'estudiantes',	'internacionales','matricula',	 null,					'admisión y matrícula'),
(113,'matricula cursos',			'cursos',		'presenciales',	'online',		'matricula',			'admisión y matrícula'),
(114,'matricula cursos verano',		'cursos',		'verano',		'matricula',	 null,					'admisión y matrícula'),
(115,'matricula mayores',			'formacion',	'mayores',		'matricula',	 null,					'admisión y matrícula'),
(116,'matricula curso espanol',		'curso',		'español',		'matricula',	'espanol',				'admisión y matrícula'),

(117,'expedicion titulos',			'expedicion',	'titulos',		 null,			 null,					'admisión y matrícula'),
(118,'reconocimiento',				'creditos',		 null,			 null,			 null,					'admisión y matrícula'),
(119,'tesis',						'doctoral',		 null,			 null,			 null,					'admisión y matrícula'),
(120,'normativa',					'academica',	 null,			 null,			 null,					'admisión y matrícula'),
(121,'seguro escolar',				'seguro',		'escolar',		 null,			 null,					'admisión y matrícula'),
(122,'seguro accidentes',			'seguro',		'accidentes',	 null,			 null,					'admisión y matrícula'),
(123,'tarjeta',						'universitaria', null,			 null,			 null,					'admisión y matrícula'),

(124,'grupos',						'unidades',		'investigacion', null,			 null,					'investigación'),
(125,'gestion',						'investigacion', null,			 null,			 null,					'investigación'),
(126,'otri',						'transferencia','investigacion', null,			 null,					'investigación'),
(127,'ubuemprede',					'emprende', 	'investigacion', null,			 null,					'investigación'),
(128,'parque cientifico',			'parque', 		'cientifico',	'tecnologico',	 'investigacion',		'investigación'),
(129,'escuela',						'doctorado', 	'investigacion', null,			 null,					'investigación'),
(130,'iccram',						'investigacion', null,			 null,			 null,					'investigación'),
(131,'campus excelencia internacional','investigacion',null,		 null,			 null,					'investigación'),

(132,'ayudas investigacion',		'ayudas',		'propias',		'investigacion', null,					'investigación'),
(133,'ayudas proyectos investigacion','ayudas',		'propias',		'investigacion', null,					'investigación'),
(134,'convocatorias investigacion',	'ayudas',		'investigacion','convocatorias', null,					'investigación'),
(135,'empresas',					'ayudas', 		'investigacion', null,			 null,					'investigación'),
(136,'emprendimiento',				'ayudas', 		'convocatorias','investigacion', null,					'investigación'),
(137,'ayudas UE',					'europa', 		'investigacion','ayudas',		 null,					'investigación'),

(138,'observatorio',				'investigacion', null,			 null,			 null,					'investigación'),
(139,'tesis investigacion',			'investigacion','tesis',		'lectura',		'defensa',				'investigación'),
(140,'propiedad',					'investigacion','industrial',	'intelectual',	 null,					'investigación'),
(141,'repositorio',					'investigacion','internacional', null,			 null,					'investigación'),

(142,'curriculum',					'cvn', 			'curriculo',	'normalizado',	'investigacion',		'investigación'),
(143,'sexenios ',					'investigacion','acreditacion',	 null,			 null,					'investigación'),
(144,'formacion',					'investigacion', null,			 null,			 null,					'investigación'),
(145,'divulgacion',					'investigacion', null,			 null,			 null,					'investigación'),
(146,'vocaciones',					'investigacion', null,			 null,			 null,					'investigación'),
(147,'ubuinvestiga',				'investigacion', null,			 null,			 null,					'investigación'),

(148,'informacion',					'internacional', null,			 null,			 null,					'internacional'),
(149,'convocatorias',				'internacional', null,			 null,			 null,					'internacional'),
(150,'estudiantes',					'internacional', null,			 null,			 null,					'internacional'),
(151,'pdi/pas',						'internacional','pdi',			'pas',			 null,					'internacional'),
(152,'dele',						'internacional','diploma',		'español',		 null,					'internacional'),
(153,'ccse',						'internacional','constitucionales','socioculturales',null,				'internacional'),
(154,'acreditacion idiomas',		'internacional','acreditacion',	'idiomas',		 null,					'internacional'),
(155,'cooperacion',					'internacional','solidaria',	 null,			 null,					'internacional'),
(156,'convenios',					'internacional', null,			 null,			 null,					'internacional'),
(157,'becas internacionales',		'internacional','becas',		'cooperacion',	 null,					'internacional'),
(158,'ububangalore',				'internacional','bangalore',	 null,			 null,					'internacional'),
(159,'ayudas pdi/pas',				'internacional','ayudas',		'pdi',			'pas',					'internacional'),
(160,'tour',						'internacional', null,			 null,			 null,					'internacional'),
(161,'aula virtual espanol',		'internacional','aula',			'virtual',		'español',				'internacional'),
(162,'alojamiento',					'internacional', null,			 null,			 null,					'internacional'),

(163,'tienda',						 null, 		 	 null,			 null,			 null,					'universidad'),
(164,'salud',						 null,			 null,			 null,			 null,					'universidad'),
(165,'caubu',						'consejo', 		'alumnos',		 null,			 null,					'universidad'),
(166,'defensor',					 null, 			 null,			 null,			 null,					'universidad'),
(167,'debate',					 	'liga',			 null,			 null,			 null,					'universidad'),
(168,'diversidad',					 null,			 null,			 null,			 null,					'universidad'),
(169,'vocacional',				 	'orientacion',	'profesional',	 null,			 null,					'universidad'),
(170,'apoyo',						'orientacion',	'tutoria',		 null,			 null,					'universidad'),
(171,'voluntariado',				 null,			 null,			 null,			 null,					'universidad'),
(172,'transparencia',				 null,			 null,			 null,			 null,					'universidad'),
(173,'tablon',				 		'oficial',		 null,			 null,			 null,					'universidad'),
(174,'normativa',				 	 null,			 null,			 null,			 null,					'universidad'),
(175,'sede',				 		'electronica',	 null,			 null,			 null,					'universidad'),
(176,'instituciones',				'empresas',	 	 null,			 null,			 null,					'universidad'),
(177,'trabajo',						'universidad',	 null,			 null,			 null,					'universidad'),

(178,'catedras',					 null,			 null,			 null,			 null,					'universidad'),
(179,'ubu',							 null,			 null,			 null,			 null,					'universidad'),
(180,'organos',						'universitarios',null,			 null,			 null,					'universidad'),
(181,'departamentos',				'centros',		 null,			 null,			 null,					'universidad'),
(182,'servicios',					 null,			 null,			 null,			 null,					'universidad'),
(183,'fundacion',					 null,			 null,			 null,			 null,					'universidad'),
(184,'representacion',				 null,			 null,			 null,			 null,					'universidad'),
(185,'directorio',					'contacto',		'direccion',	'telefono',		'mail',					'universidad'),

(186,'cultura',						'musica',		'cine',			'teatro',		'exposiciones',			'universidad'),
(187,'deporte',						'bici',			'esqui',		'senderismo',	'actividades',			'universidad'),
(188,'wifi',						'wi-fi',		'internet',		 null,			 null,					'universidad'),
(189,'ubunet',						 null,			 null,			 null,			 null,					'universidad'),
(190,'ubuvirtual',					 null,			'virtual',		 null,			 null,					'universidad'),
(191,'asociaciones',				'estudiantes',	 null,			 null,			 null,					'universidad'),
(192,'ubuventajas',					'ventajas',		 null,			 null,			 null,					'universidad'),

(193,'secretaria',					'virtual',		 null,			 null,			 null,					'universidad'),
(194,'biblioteca',					'recursos',		'libros',		'ubucat',		 null,					'universidad'),
(195,'alumnos',						'antiguos',		 null,			 null,			 null,					'universidad'),
(196,'noticias',					null,			 null,			 null,			 null,					'universidad'),
(197,'agenda',						null,			 null,			 null,			 null,					'universidad'),
(198,'te interesa',					'interesa',		 null,			 null,			 null,					'universidad'),

(199,'correo',						'office365',	 '365',			 null,			 null,					'recursos'),
(200,'intranet',					null,			 null,			 null,			 null,					'recursos'),
(201,'repositorio',					'internacional', null,			 null,			 null,					'recursos'),
(202,'archivo',						'general', 		 null,			 null,			 null,					'recursos'),
(203,'normativa',					 null, 			 null,			 null,			 null,					'recursos'),
(204,'boubu',						'boletion',	 	'oficial',		 null,			 null,					'recursos'),

(205,'dircom',						'direccion',	'comunicaciones', null,			 null,					'recursos'),
(206,'gabinete',					'comunicacion',	 null,			 null,			 null,					'recursos'),
(207,'actualidad',					 null,			 null,			 null,			 null,					'recursos'),
(208,'tvubu',					 	'television',	 null,			 null,			 null,					'recursos'),
(209,'uburadio',				 	'radio',		 null,			 null,			 null,					'recursos'),
(210,'protocolo',				 	 null,			 null,			 null,			 null,					'recursos'),
(211,'divulgacion',				 	'cientifica',	 null,			 null,			 null,					'recursos'),
(212,'publicaciones',			 	'imagen',	 	'institucional', null,			 null,					'recursos'),
(213,'buscapersonas',			 	'busca',	 	'personas', 	 null,			 null,					'recursos'),
(214,'privacidad',				 	 null,	 		 null, 	 		 null,			 null,					'recursos'),
(215,'zona privada',				'zona',	 		'privada', 		 null,			 null,					'recursos'),
(216,'twitter',						'redes',	 	'sociales', 	 null,			 null,					'recursos'),
(217,'facebook',					'redes',	 	'sociales', 	 null,			 null,					'recursos'),
(218,'instagram',					'redes',	 	'sociales', 	 null,			 null,					'recursos'),
(219,'youtube',						'redes',	 	'sociales', 	 null,			 null,					'recursos'),
(220,'ubuapp',						'app',	 		'aplicacion', 	'movil',		 null,					'recursos'),

(221,'honoris',						'causa',		 null,			 null,			 null,					'universidad')
;	




drop table if exists casesolution;
create table casesolution(
id int(100) primary key AUTO_INCREMENT,
  answer varchar(1000) NOT NULL
);


INSERT INTO casesolution ( id, answer )
VALUES
(1, 'http://www.ubu.es/titulos-online'),
(2, 'http://www.ubu.es/grado-oficial-online-en-espanol-lengua-y-literatura'),
(3, 'http://www.ubu.es/grado-en-espanol-lengua-y-literatura'),
(4, 'http://www.ubu.es/grado-oficial-online-en-historia-y-patrimonio'),
(5, 'http://www.ubu.es/grado-en-historia-y-patrimonio'),
(6, 'http://www.ubu.es/grado-en-quimica'),
(7, 'http://www.ubu.es/grado-en-ciencia-y-tecnologia-de-los-alimentos'),
(8, 'http://www.ubu.es/grado-en-enfermeria'),
(9, 'http://www.ubu.es/grado-en-terapia-ocupacional'),
(10,'http://www.ubu.es/doble-grado-en-derecho-y-administracion-y-direccion-de-empresas'),
(11,'http://www.ubu.es/doble-grado-en-derecho-y-en-ciencia-politica-y-gestion-publica'),
(12,'http://www.ubu.es/grado-en-administracion-y-direccion-de-empresas-bilingue-espanol'),
(13,'http://www.ubu.es/grado-oficial-online-en-ciencia-politica-y-gestion-publica'),
(14,'http://www.ubu.es/grado-en-ciencia-politica-y-gestion-publica'),
(15,'http://www.ubu.es/grado-en-comunicacion-audiovisual'),
(16,'http://www.ubu.es/grado-en-derecho'),
(17,'http://www.ubu.es/grado-en-educacion-social'),
(18,'http://www.ubu.es/grado-en-finanzas-y-contabilidad'),
(19,'http://www.ubu.es/grado-en-maestro-de-educacion-infantil'),
(20,'http://www.ubu.es/grado-en-maestro-de-educacion-primaria'),
(21,'http://www.ubu.es/grado-en-pedagogia'),
(22,'http://www.ubu.es/grado-en-relaciones-laborales-y-recursos-humanos'),
(23,'http://www.ubu.es/grado-oficial-online-en-turismo'),
(24,'http://www.ubu.es/grado-en-turismo'),
(25,'http://www.ubu.es/doble-grado-en-ingenieria-civil-y-en-arquitectura-tecnica'),
(26,'http://www.ubu.es/doble-grado-en-ingenieria-de-tecnologias-de-caminos-y-en-arquitectura-tecnica'),
(27,'http://www.ubu.es/doble-grado-en-ingenieria-mecanica-e-ingenieria-electronica-industrial-y-automatica'),
(28,'http://www.ubu.es/grado-en-arquitectura-tecnica'),
(29,'http://www.ubu.es/grado-en-ingenieria-agroalimentaria-y-del-medio-rural'),
(30,'http://www.ubu.es/grado-en-ingenieria-civil'),
(31,'http://www.ubu.es/grado-en-ingenieria-de-organizacion-industrial-espanol-y-bilingue-en-ingles'),
(32,'http://www.ubu.es/grado-en-ingenieria-de-tecnologias-de-caminos'),
(33,'http://www.ubu.es/grado-en-ingenieria-electronica-industrial-y-automatica'),
(34,'http://www.ubu.es/grado-oficial-online-en-ingenieria-informatica'),
(35,'http://www.ubu.es/grado-en-ingenieria-informatica'),
(36,'http://www.ubu.es/grado-en-ingenieria-mecanica'),

(37,'http://www.ubu.es/master-universitario-en-patrimonio-y-comunicacion'),
(38,'http://www.ubu.es/master-universitario-en-cultura-del-vino-enoturismo-en-la-cuenca-del-duero-semipresencial'),
(39,'http://www.ubu.es/master-universitario-en-quimica-avanzada'),
(40,'http://www.ubu.es/master-universitario-en-evolucion-humana-interuniversitario'),
(41,'http://www.ubu.es/master-universitario-en-electroquimica-ciencia-y-tecnologia-interuniversitario'),
(42,'http://www.ubu.es/master-universitario-en-seguridad-y-biotecnologia-alimentarias'),
(43,'http://www.ubu.es/curso-de-formacion-pedagogica-y-didactica'),
(44,'http://www.ubu.es/master-universitario-en-acceso-la-abogacia'),
(45,'http://www.ubu.es/master-universitario-en-administracion-de-empresas-mba'),
(46,'http://www.ubu.es/master-universitario-en-comunicacion-y-desarrollo-multimedia'),
(47,'http://www.ubu.es/master-universitario-en-contabilidad-avanzada-y-auditoria-de-cuentas-semipresencial'),
(48,'http://www.ubu.es/estudios/oferta-de-estudios/masteres-universitarios-oficiales/ciencias-sociales-y-juridicas/master-universitario-en-cooperacion-internacional-para-el-desarrollo-interuniversitario'),
(49,'http://cms.ual.es/UAL/estudios/masteres/MASTER7073'),
(50,'http://www.ubu.es/master-universitario-en-educacion-y-sociedad-inclusivas'),
(51,'http://www.ubu.es/facultad-de-ciencias-economicas-y-empresariales/informacion-academica/masteres/master-universitario-en-investigacion-en-administracion-y-economia-de-la-empresa-interuniversitario'),
(52,'http://www.ubu.es/master-universitario-en-profesor-de-educacion-secundaria-obligatoria-y-bachillerato-formacion-profesional-y-ensenanza-de-idiomas'),
(53,'http://www.ubu.es/master-universitario-en-ingenieria-informatica'),
(54,'http://www.ubu.es/master-universitario-online-en-ingenieria-informatica'),
(55,'http://www.ubu.es/master-universitario-en-ingenieria-industrial'),
(56,'http://www.ubu.es/master-universitario-en-ingenieria-y-gestion-agrosostenible-semipresencial'),
(57,'http://www.ubu.es/master-universitario-en-ingenieria-de-caminos-canales-y-puertos'),
(58,'http://www.ubu.es/master-universitario-en-inspeccion-rehabilitacion-y-eficiencia-energetica-en-la-edificacion'),
(59,'http://www.ubu.es/master-universitario-online-en-inspeccion-rehabilitacion-y-eficiencia-energetica-en-la-edificacion'),
(60,'http://www.ubu.es/master-universitario-en-integridad-y-durabilidad-de-materiales-componentes-y-estructuras-interuniversitario'),

(61,'http://www.ubu.es/estudios/oferta-de-estudios/titulos-propios'),
(62,'http://www.ubu.es/centro-de-lenguas-modernas-modern-language-centre'),
(63,'http://www.ubu.es/cursos-internacionales-cursos-de-espanol'),
(64,'http://www.ubu.es/estudios/oferta-de-estudios/licenciaturas-e-ingenierias-extinguir'),
(65,'http://www.ubu.es/ubuabierta-cursos-de-extension-universitaria/cursos-ubuabierta/cursos-ubuabierta-presenciales'),
(66,'http://www.ubu.es/ubuabierta-cursos-de-extension-universitaria/cursos-ubuabierta/cursos-ubuabierta-online'),
(67,'http://www.ubu.es/ubuabierta-cursos-de-extension-universitaria/cursos-0-cursos-complementarios-de-preparacion-para-el-inicio-de-una-carrera-universitaria'),
(68,'http://www.ubu.es/cursos-de-verano-de-la-universidad-de-burgos'),
(69,'http://www.ubu.es/ubuabierta-cursos-de-extension-universitaria/campus-infantiles'),
(70,'http://www.ubu.es/ubuabierta-cursos-de-extension-universitaria/formacion-de-mayores'),

(71,'http://www.ubu.es/la-universidad/organizacion/centros-y-departamentos'),
(72,'http://www.ubu.es/ayudas-y-becas'),
(73,'http://www.ubu.es/vicerrectorado-de-politicas-academicas/ordenacion-academica/calendarios-academicos'),
(74,'http://www.ubu.es/acceso-admision-y-matricula/tramites-academicos'),
(75,'http://www.ubu.es/vicerrectorado-de-profesorado-y-personal-de-administracion-y-servicios/calidad-de-la-docencia'),
(76,'http://www.ubu.es/servicio-de-empleo-universitario-unidad-de-empleo'),
(77,'http://www.ubu.es/acceso-admision-y-matricula/admision/formacion-permanente-y-complementaria'),
(78,'http://www.ubu.es/vicerrectorado-de-ordenacion-academica-y-calidad/acceso-al-curriculum-abreviado-del-profesorado-de-la-ubu'),

(79,'http://www.ubu.es/estudios/oferta-de-estudios'),
(80,'http://www.ubu.es/ubuabierta-cursos-de-extension-universitaria'),
(81,'http://www.ubu.es/doctorado-en-avances-en-ciencia-y-biotecnologia-alimentarias'),
(82,'http://www.ubu.es/doctorado-en-tecnologias-industriales-e-ingenieria-civil'),
(83,'http://www.ubu.es/doctorado-en-quimica-avanzada'),
(84,'http://www.ubu.es/escuela-de-doctorado/programas-de-doctorado/oferta-de-estudios-de-la-escuela-de-doctorado-curso-academico-20152016/investigacion-en-ingenieria-termodinamica-de-fluidos'),
(85,'http://www.ubu.es/doctorado-en-humanidades-y-comunicacion'),
(86,'http://www.ubu.es/escuela-de-doctorado/programas-de-doctorado/oferta-de-estudios-de-la-escuela-de-doctorado-curso-academico-20152016/electroquimica-ciencia-y-tecnologia-interuniversitario'),
(87,'http://www.ubu.es/escuela-de-doctorado/programas-de-doctorado/oferta-de-estudios-de-la-escuela-de-doctorado-curso-academico-20152016/eficiencia-energetica-y-sostenibilidad-en-ingenieria-y'),
(88,'http://www.ubu.es/doctorado-en-educacion'),
(89,'http://www.ubu.es/escuela-de-doctorado/programas-de-doctorado/oferta-de-estudios-de-la-escuela-de-doctorado-curso-academico-20152016/economia-de-la-empresa-interuniversitario'),
(90,'http://www.ubu.es/doctorado-interuniversitario-de-evolucion-humana-paleoecologia-del-cuaternario-y-tecnicas-geofisicas-aplicadas-la-investigacion'),
(91,'http://www.ubu.es/doctorado-en-ciencias-juridicas-economicas-y-sociales'),

(92,'http://www.ubu.es/acceso-admision-y-matricula/matricula'),
(93,'http://www.ubu.es/acceso-admision-y-matricula/acceso'),
(94,'http://www.ubu.es/acceso-admision-y-matricula/acceso/prueba-de-acceso-ensenanzas-universitarias-bachillerato'),
(95,'http://www.ubu.es/acceso-admision-y-matricula/acceso/prueba-de-acceso-ensenanzas-universitarias-ciclos-formativos-de-grado-superior'),
(96,'http://www.ubu.es/acceso-admision-y-matricula/acceso/pruebas-de-acceso-mayores-de-25-anos'),
(97,'http://www.ubu.es/acceso-admision-y-matricula/acceso/pruebas-de-acceso-mayores-de-45-anos'),
(98,'http://www.ubu.es/acceso-admision-y-matricula/acceso/acceso-experiencia-laboral-y-profesional-mayores-de-40-anos'),
(99,'http://www.ubu.es/acceso-admision-y-matricula/admision'),
(100,'http://www.ubu.es/acceso-admision-y-matricula/admision/admision-grado'),
(101,'http://www.ubu.es/acceso-admision-y-matricula/admision/admision-master'),
(102,'http://www.ubu.es/escuela-de-doctorado/preinscripcion-y-admision-doctorado-rd-992011-curso-academico-20162017'),
(103,'http://www.ubu.es/estudios/oferta-de-estudios/titulos-propios-de-posgrado/admision-y-matricula'),
(104,'http://www.ubu.es/acceso-admision-y-matricula/admision/formacion-permanente-y-complementaria'),
(105,'http://www.ubu.es/acceso-admision-y-matricula/admision/estudiantes-visitantes'),
(106,'http://www.ubu.es/acceso-admision-y-matricula/admision/estudiantes-con-estudios-extranjeros'),

(107,'http://www.ubu.es/acceso-admision-y-matricula/matricula/matricula-de-grado'),
(108,'http://www.ubu.es/acceso-admision-y-matricula/matricula/matricula-de-master'),
(109,'http://www.ubu.es/escuela-de-doctorado/matricula-de-doctorado'),
(110,'https://limbo.ubu.es/campusvirtual/MatriculaEP/index.asp'),
(111,'http://www.ubu.es/acceso-admision-y-matricula/matricula/matricula-de-estudios-de-primer-y-segundo-ciclo'),
(112,'http://www.ubu.es/servicio-de-relaciones-internacionales/estudiantes-internacionales/admision-matricula'),
(113,'https://tarjeta.ubu.es:18443/UbuAbierta/ppal.jsp'),
(114,'https://tarjeta.ubu.es:18443/preinscCV/ppal.jsp'),
(115,'http://www.ubu.es/ubuabierta-cursos-de-extension-universitaria/formacion-de-mayores'),
(116,'http://www.ubu.es/cursos-internacionales-cursos-de-espanol/cursos/formulario-de-admision-y-matricula'),

(117,'http://www.ubu.es/acceso-admision-y-matricula/tramites-academicos/expedicion-de-titulos-y-set'),
(118,'http://www.ubu.es/acceso-admision-y-matricula/tramites-academicos/reconocimiento-de-creditos'),
(119,'http://www.ubu.es/escuela-de-doctorado/tesis-doctoral'),
(120,'http://www.ubu.es/servicio-de-gestion-academica/normativa-en-gestion-academica'),
(121,'http://www.ubu.es/servicio-de-gestion-academica/servicios-de-gestion-academica/seguro-escolar'),
(122,'http://www.ubu.es/acceso-admision-y-matricula/matricula/matricula-de-grado/seguro'),
(123,'http://www.ubu.es/servicio-de-gestion-academica/servicios-de-gestion-academica/tarjeta-universitaria-inteligente'),

(124,'http://www.ubu.es/otri-transferencia/grupos-de-investigacion-y-unidades-de-investigacion-consolidada'),
(125,'http://www.ubu.es/servicio-de-gestion-de-la-investigacion'),
(126,'http://www.ubu.es/otri-transferencia'),
(127,'http://www.ubu.es/ubuemprende'),
(128,'http://www.ubu.es/parque-cientifico-tecnologico'),
(129,'http://www.ubu.es/escuela-de-doctorado'),
(130,'http://www.ubu.es/iccram'),
(131,'http://ceitriangular.org/'),

(132,'http://www.ubu.es/te-interesa/busqueda?keys=&field_term_interest_tid=122&field_portal_father_article_target_id=All'),
(133,'http://www.ubu.es/te-interesa/busqueda?keys=&field_term_interest_tid=123&field_portal_father_article_target_id=All'),
(134,'https://investigacion.ges.ubu.es/Investigacion/publico/convocatorias/EditarConsultaEntidadCv.do?modulo=cur&inicioNav=1'),
(135,'http://www.ubu.es/otri-transferencia/convocatorias-y-ayudas-colaboracion-universidad-empresa/convocatorias-nacionales-universidad-empresa'),
(136,'http://www.ubu.es/ubuemprende/convocatorias-prototipo'),
(137,'http://www.ubu.es/investigacion/convocatorias-y-ayudas/fondos-de-la-ue'),

(138,'http://www3.ubu.es/ubuinvestiga/?page_id=329'),
(139,'http://www.ubu.es/escuela-de-doctorado/tesis-doctoral/lectura-y-defensa-de-tesis'),
(140,'http://www.ubu.es/otri-transferencia/propiedad-industrial-e-intelectual'),
(141,'http://riubu.ubu.es/'),

(142,'http://www.ubu.es/investigacion/apoyo-al-investigador/cvn-curriculum-vitae-normalizado'),
(143,'http://www.ubu.es/aprendizaje-e-investigacion/sexenios-y-acreditacion'),
(144,'http://www.ubu.es/divulgacion-cientifica-ucci-ubu/formacion'),
(145,'http://www.ubu.es/divulgacion-cientifica-ucci-ubu/divulgacion-cientifica'),
(146,'http://www.ubu.es/divulgacion-cientifica-ucci-ubu/vocaciones-cientificas'),
(147,'http://ubuinvestiga.ubu.es/'),

(148,'http://www.ubu.es/servicio-de-relaciones-internacionales'),
(149,'http://www.ubu.es/becas-de-movilidad?keys=&field_portal_father_article_target_id=All&field_term_interest_tid=148'),
(150,'http://www.ubu.es/servicio-de-relaciones-internacionales/estudiantes-ubu-internacional'),
(151,'http://www.ubu.es/servicio-de-relaciones-internacionales/paspdi-internacional'),
(152,'http://www.ubu.es/cursos-internacionales-cursos-de-espanol/dele-diploma-de-espanol-como-lengua-extranjera'),
(153,'http://www.ubu.es/cursos-internacionales-cursos-de-espanol/ccse-conocimientos-constitucionales-y-socioculturales-de-espana'),
(154,'http://www.ubu.es/centro-de-lenguas-modernas-modern-language-centre/acreditacion-de-idiomas'),
(155,'http://www.ubu.es/centro-de-cooperacion-y-accion-solidaria'),
(156,'http://www.ubu.es/centro-de-cooperacion-y-accion-solidaria/informacion-general/convenios'),
(157,'http://www.ubu.es/becas-de-cooperacion'),
(158,'http://ubu-bangalore.blogspot.com.es/'),
(159,'http://www.ubu.es/centro-de-cooperacion-y-accion-solidaria/becas-convocatorias-y-ayudas/ubu-ayudas-para-acciones-de-cooperacion-universitaria-al-desarrollo-para-el-pdipas-2014'),
(160,'https://www.youtube.com/watch?v=kF2-pjk1G4g&noredirect=1'),
(161,'http://www.ave.cvc.cervantes.es/login.asp?numtira=4&s='),
(162,'http://www.ubu.es/servicio-de-informacion-y-extension-universitaria/servicios-unidad-de-informacion/alojamiento-para-universitarios'),

(163,'http://www3.ubu.es/ubuespacio/'),
(164,'http://www.ubu.es/servicio-de-informacion-y-orientacion-en-salud-joven-universitaria'),
(165,'http://www.ubu.es/caubu-consejo-de-alumnos-de-la-universidad-de-burgos'),
(166,'http://www.ubu.es/defensor-universitario'),
(167,'http://www.ubu.es/servicio-de-informacion-y-extension-universitaria/servicios-unidad-de-extension-universitaria/ligas-de-debate'),
(168,'http://www.ubu.es/unidad-de-atencion-la-diversidad'),
(169,'http://www.ubu.es/servicio-de-empleo-universitario-unidad-de-empleo/orientacion-coaching-y-formacion/orientacion-vocacional-y-profesional'),
(170,'http://www.ubu.es/servicio-de-estudiantes-y-extension-universitaria/servicios-unidad-de-informacion/orientacion-y-tutoria-de-apoyo'),
(171,'http://www.ubu.es/voluntariado'),
(172,'http://www.ubu.es/portal-de-transparencia'),
(173,'http://www.ubu.es/registro-e-informacion/tablon-oficial-de-la-ubu'),
(174,'http://www.ubu.es/normativa'),
(175,'https://sede.ubu.es/opencms/opencms/es'),
(176,'http://www.ubu.es/empresas-e-instituciones'),
(177,'http://www.ubu.es/trabaja-en-la-ubu'),

(178,'http://www.ubu.es/la-universidad/la-ubu/catedras-de-la-universidad-de-burgos'),
(179,'http://www.ubu.es/la-universidad/la-ubu'),
(180,'http://www.ubu.es/la-universidad/organizacion/organos-universitarios'),
(181,'http://www.ubu.es/la-universidad/organizacion/centros-y-departamentos'),
(182,'http://www.ubu.es/la-universidad/organizacion/servicios-universitarios'),
(183,'http://www.fundacionubu.com/es/portada/'),
(184,'http://www.ubu.es/la-universidad/organizacion/organos-universitarios/organos-de-representacion'),
(185,'http://www.ubu.es/la-universidad/organizacion/directorio'),

(186,'http://www.ubu.es/cultura'),
(187,'http://www.ubu.es/deportes'),
(188,'http://www.ubu.es/servicio-de-informatica-y-comunicaciones/catalogo-de-servicios/red-wifi-vpn/wi-fi'),
(189,'https://ubunet.ubu.es/co/pag/index.htm'),
(190,'https://ubuvirtual.ubu.es/'),
(191,'http://www.ubu.es/servicio-de-informacion-y-extension-universitaria/servicios-unidad-de-informacion/asociaciones-de-estudiantes'),
(192,'http://www.ubu.es/ubuventajas'),

(193,'https://secretariavirtual.ubu.es'),
(194,'http://www.ubu.es/biblioteca'),
(195,'http://www.aaaaubu.es/'),
(196,'http://www.ubu.es/noticias'),
(197,'http://www.ubu.es/agenda'),
(198,'http://www.ubu.es/te-interesa'),

(199,'https://login.microsoftonline.com'),
(200,'https://www.ubu.es/user?destination=node/46604'),
(201,'http://riubu.ubu.es/'),
(202,'http://www.ubu.es/archivo-general'),
(203,'http://www.ubu.es/normativa'),
(204,'http://www.ubu.es/normativa/normativa-de-gobierno-de-la-universidad/boletin-oficial-de-la-ubu-boubu'),

(205,'http://www.ubu.es/direccion-de-comunicacion-dircom'),
(206,'http://www.ubu.es/gabinete-de-comunicacion'),
(207,'http://www3.ubu.es/actualidad/'),
(208,'http://www3.ubu.es/actualidad/tvubu/'),
(209,'http://www3.ubu.es/actualidad/uburadio/'),
(210,'http://www.ubu.es/unidad-de-protocolo'),
(211,'http://www.ubu.es/divulgacion-cientifica-ucci-ubu'),
(212,'http://www.ubu.es/servicio-de-publicaciones-e-imagen-institucional'),
(213,'https://www3.ubu.es/buscapersonas/'),
(214,'http://www.ubu.es/politica-de-privacidad'),
(215,'https://www.ubu.es/user'),
(216,'https://twitter.com/UBUEstudiantes'),
(217,'https://www.facebook.com/Universidad.Burgos'),
(218,'https://www.instagram.com/universidadburgos/'),
(219,'https://www.youtube.com/user/tvubu'),
(220,'https://play.google.com/store/apps/details?id=com.pocketuniversity.ubu'),

(221,'http://www.ubu.es/unidad-de-protocolo/actos-academicos-solemnes/doctorado-honoris-causa')
;


drop table if exists saludos;
create table saludos(
id int(10) primary key AUTO_INCREMENT,
saludo varchar(1000) NOT NULL,
respuesta varchar(1000) NOT NULL
);


INSERT INTO saludos ( id, saludo, respuesta)
VALUES
(1,'Hola','Hola, estoy preparada para responder, adelánte'),
(2,'Buenos dias','Buenos días, ponme a prueba con tus preguntas'),
(3,'Buenas tardes','Buenas tardes, ¿tienes alguna duda? No dudes en preguntarme'),
(4,'Buenas noches','Buenas noches, ¿qué te apetece preguntar?'),
(5,'Buenas','Muy buenas serán si te contesto correctamente'),
(6,'Adios','¡Adiós!, espero haberte servido de ayuda'),
(7,'Hasta luego','Hasta luego, espero que volvamos a vernos'),
(8,'Ciao','¡Arrivederci!'),
(9,'Eres una pesada','No te pongas así, seguro que podemos tener una conversación productiva'),
(10,'Callate','Lo siento, solo intentaba ayudar');

drop table if exists frases;
create table frases(
id int(10) primary key AUTO_INCREMENT,
frase varchar(1000) NOT NULL
);

INSERT INTO frases (id, frase)
VALUES
(1,'Hola soy UBUassistant, ¿en qué puedo ayudarte?'),
(2,'Muy buenas, me llamo UBUassistant y estoy lista para ayudarte ¡adelante!'),
(3,'Hola, si necesitas ayuda aquí me tienes, aquí tienes a UBUassistant'),
(4,'Bienvenido, ante cualquier duda de tu universidad UBUassistant al rescate'),
(5,'UBUassistant te da la bienvenida, ¿Empezamos?, pregunta cualquier duda sobre la UBU'),
(6,'Tal vez esto te ayude'),
(7,'Prueba con la siguiente información'),
(8,'Espero que esto te ayude'),
(9,'Esto es lo que he encontrado al respecto'),
(10,'Aquí tienes mis respuestas');

drop table if exists aprendizaje;
create table aprendizaje(
id int(100) primary key AUTO_INCREMENT,
userid varchar(1000) NOT NULL,
palabra1 varchar(1000) NOT NULL,
palabra2 varchar(1000) NOT NULL
);

drop table if exists logger;
create table logger(
id int(10) primary key AUTO_INCREMENT,
userid varchar(1000) NOT NULL,
fecha datetime NOT NULL,
keyWord1 varchar(1000),
keyWord2 varchar(1000),
keyWord3 varchar(1000),
keyWord4 varchar(1000),
keyWord5 varchar(1000),
categoria varchar(1000),
respuesta varchar(1000),
num_busquedas int(10) NOT NULL,
num_votos int(10),
valoracion_total int(10)
);


drop table if exists administradores;
create table administradores(
id int(10) primary key AUTO_INCREMENT,
mail varchar(300) NOT NULL,
contrasena varchar(300) NOT NULL
);

INSERT INTO administradores (id, mail, contrasena)
VALUES
(1,'admin1@ubu.es','admin1'),
(2,'admin2@ubu.es','admin2'),
(3,'admin3@ubu.es','admin3');